# Generated by Django 2.2.1 on 2019-05-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='department',
            field=models.CharField(choices=[('Finance', 'Finance'), ('Credit and Risk', 'Credit and Risk'), ('Sales and Collection', 'Sales and Collection'), ('IT', 'IT'), ('Sales Operations', 'Sales Operations'), ('Consumer Loans', 'Consumer Loans'), ('Documentation and Records', 'Documentation and Records'), ('HRAD', 'HRAD'), ('Spare Parts', 'Spare Parts'), ('Supply Chain', 'Supply Chain'), ('Audit', 'Audit'), ('Service', 'Service'), ('Engineering', 'Engineering'), ('Treasury', 'Treasury'), ('Marketing', 'Marketing'), ('Legal', 'Legal'), ('Operations', 'Operations'), ('Insurance', 'Insurance'), ('Tax Compliance', 'Tax Compliance'), ('Financial Planning', 'Financial Planning'), ('Opcom', 'Opcom')], max_length=40, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Name'),
        ),
    ]
