# Generated by Django 2.2.1 on 2019-05-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190530_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Full Name'),
        ),
    ]
