# Generated by Django 2.2.1 on 2019-06-03 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_usersmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
